version: "3.3"
services:
  repository:
    build:
      context: ./repository/
      args:
        ENABLED_MODULES: fancyindex
    image: interlis-model-repository:latest
    volumes:
      - validated-repository:/data:ro
    ports:
      - "8080:80"

  validator:
    build:
      context: ./repository-validator/
    image: interlis-model-repository-validator:latest
    volumes:
      - ./dummy-repository-data:/input
      - validated-repository:/output

volumes:
  validated-repository: {}
